<!-- Optional JavaScript -->
<script src="{{ asset('assets/frontend/js/jquery.min.js') }}"></script>
<script src="{{ asset('assets/frontend/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/frontend/select2/js/select2.min.js') }}"></script>
<script src="{{ asset('assets/frontend/matchHeight/js/matchHeight-min.js') }}"></script>
<script src="{{ asset('assets/frontend/bxslider/js/bxslider.min.js') }}"></script>
<script src="{{ asset('assets/frontend/waypoints/js/waypoints.min.js') }}"></script>
<script src="{{ asset('assets/frontend/counterup/js/counterup.min.js') }}"></script>
<script src="{{ asset('assets/frontend/magnific-popup/js/magnific-popup.min.js') }}"></script>
<script src="{{ asset('assets/frontend/owl-carousel/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('assets/frontend/js/modernizr.custom.js') }}"></script>
<script src="{{ asset('assets/frontend/js/custom.js') }}"></script>